project:
  type: website
  output-dir: "."

website:
  title: "Data Analytics Project"
  navbar:
    pinned: true
    left:
      - text: DANL 200
        href: project.qmd
      - text: DANL 210
        href: danl_proj_nba.ipynb
      - text: Blog
        href: blog-listing.qmd
      - text: Python Data Analysis
        menu:
          - text: Pandas Basics
            href: pandas_basics.ipynb
          - text: Seaborn Basics
            href: seaborn_basics.ipynb
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© YOUR NAME, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
